debug: true
server:
  port: ${port:8081}

security:
  ignored: /,/favicon.ico,/js/**,/css/**,/webjars/**,/ws/**,/error
  sessions: ALWAYS

---
spring:
  profiles: default
security:
  oauth2:
    client:
      clientId: ~ # @TODO: These should come from ENV vars or Config Service
      clientSecret: ~
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user
      preferTokenInfo: false

---
spring:
  profiles: prod
server:
  port : ${port:80}
